### ISSUE TITLE
Where are AllowWindowsPlatformTypes.h and HideWindowsPlatformTypes.h

### ISSUE THREAD

**Issue by qiuwch** [code4game/libprotobuf#1]
In your document you mentioned
```
#include "AllowWindowsPlatformTypes.h" //< before include the header file
#include "your code header file" //< ex: #include "Message.pb.h"
#include "HideWindowsPlatformTypes.h"
```
But I can not find these two files anywhere.

**Comment by alexchicn** [comment]
You can find in UnrealEngine\Engine\Source\Runtime\Core\Public\Windows\AllowWindowsPlatformTypes.h and UnrealEngine\Engine\Source\Runtime\Core\Public\Windows\HideWindowsPlatformTypes.h.
That is just for the **window development**.
