### ISSUE TITLE
Adding to new UE4 project

### ISSUE THREAD

**Issue by Renanse** [code4game/libprotobuf#2]
Placing this into ThirdParty folder as instructed does not appear to allow UE4 to find it as a module.  Is there some other configuration I need to make to my project for Unreal to find this module?

> 1>------ Build started: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
2>------ Build started: Project: TestProject1, Configuration: Shipping_Game x64 ------
2>  Creating makefile for TestProject1 (changes to module files)
2>EXEC : error : Couldn't find module rules file for module 'libprotobuf'.

**Comment by alexchicn** [comment]
@Renanse Can you see the libprotobuf in the visual studio? Do you regenerate the visual studio solution by UE4 version selector? And which version do you use?

**Comment by Renanse** [comment]
I did regen in UE4, but it seems to only find the module if I place it
under Source in my project.

In other words, this works:

`D:\UnrealProjects\TestProject1\Source\ThirdParty\libprotobuf`

But this does not:

`D:\UnrealProjects\TestProject1\ThirdParty\libprotobuf`

**Comment by Renanse** [comment]
Oh, I am using UE 4.14.3 and Visual Studio 2015 if that is helpful.

**Comment by alexchicn** [comment]
Yes, you are right, and need add to the `Source` directory.

In common, the third party was placed in the `Source` directory of module or plugin.
Sorry, this is my mistake in [README](https://github.com/code4game/libprotobuf/blob/master/README.md). And I fixed it in [this commit](https://github.com/code4game/libprotobuf/commit/7f0ffafd58ee15063a05c6a7cc782309c984bba2).

Thanks a lot. @Renanse
